version: "3.3"
services:
    backend:
        container_name: backend
        image: backend-app
        restart: on-failure
        build:
            context: ./backend/dsSystems
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
            - DATABASE_URL=jdbc:postgresql://db:5432/distributed_systems
        volumes:
            - postgres:/var/lib/postgresql/data
    db:
        container_name: dspgdb
        image: postgres:15.3-alpine
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
            #- DATABASE_URL=jdbc:postgresql://localhost:5432/distributed_systems
            - POSTGRES_DB=distributed_systems
        volumes:
            - pgdata:/var/lib/postgresql/data
    #frontend:
      #  container_name: dsfrontend
     #   image: frontend
       # build:
        #    context: ./frontend
        #command: npm start
        #ports:
         #   - "4200:80"
        #depends_on:
         #   - backend       
         
volumes:
  pgdata:
  node_modules:
  postgres:

