spring:
    devtools:
      add-properties: false 
    application:
      name: dsSystems
    datasource:
      url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/distributed_systems}
      driverClassName: org.postgresql.Driver
      username: ${DATABASE_USERNAME:postgres}
      password: ${DATABASE_PASSWORD:postgres}  
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database: postgresql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          generate_statistics: true
management: 
  server:
    port: 8080
  security: 
    enabled: false
  health:
    db: 
      enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus
    